network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: true
      optional: true
    enp0s8:
      dhcp4: no
      addresses: [192.168.56.10/24]
    enp0s9:
      dhcp4: no
      addresses: [192.168.100.10/24]
